name: Aaron Rumery
description: Software Engineer
avatar: https://raw.githubusercontent.com/bloodhawk/bloodhawk.github.io/master/me.jpeg

footer-links:
  email: aaronrumery@gmail.com
  github: bloodhawk
  linkedin: aaron-rumery
  stackoverflow: users/3435266/aaron-rumery
  rss: feed


# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

url: http://bloodhawk.github.io

baseurl: ""
permalink: /:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
sass:
  style: :expanded
gems:
  - jekyll-sitemap
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
